[package]
name = "sgkind-utils"
version = "0.1.0"
authors = ["sgkind <sunguanke11@mails.ucas.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
